// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUPf1nrM5pWEk88oXpnKhWqyeFoOqlUSA',
    appId: '1:71785141838:web:c6f6aa0261809eec1f551f',
    messagingSenderId: '71785141838',
    projectId: 'connectcall-3a6ce',
    authDomain: 'connectcall-3a6ce.firebaseapp.com',
    storageBucket: 'connectcall-3a6ce.firebasestorage.app',
    measurementId: 'G-GSME6Q3LWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRPePgRVntlg6DB4QfyLjiMsAm99OuVcE',
    appId: '1:71785141838:android:8156ceb352e00ebb1f551f',
    messagingSenderId: '71785141838',
    projectId: 'connectcall-3a6ce',
    storageBucket: 'connectcall-3a6ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzqa149pv6CcPw2ZzyoeVc0ttyDz6Q-I0',
    appId: '1:71785141838:ios:1b054736f2465ce81f551f',
    messagingSenderId: '71785141838',
    projectId: 'connectcall-3a6ce',
    storageBucket: 'connectcall-3a6ce.firebasestorage.app',
    iosBundleId: 'com.example.connectcall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzqa149pv6CcPw2ZzyoeVc0ttyDz6Q-I0',
    appId: '1:71785141838:ios:1b054736f2465ce81f551f',
    messagingSenderId: '71785141838',
    projectId: 'connectcall-3a6ce',
    storageBucket: 'connectcall-3a6ce.firebasestorage.app',
    iosBundleId: 'com.example.connectcall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUPf1nrM5pWEk88oXpnKhWqyeFoOqlUSA',
    appId: '1:71785141838:web:301dd89ffb1a793c1f551f',
    messagingSenderId: '71785141838',
    projectId: 'connectcall-3a6ce',
    authDomain: 'connectcall-3a6ce.firebaseapp.com',
    storageBucket: 'connectcall-3a6ce.firebasestorage.app',
    measurementId: 'G-CPEFXCGXYS',
  );
}
